### ISSUE TITLE
Mismatch between code and docstring

### ISSUE THREAD

**Issue by alexander-lazarov** [gregorleban/EventRegistry#1]
Found a small issue here:
https://github.com/gregorleban/EventRegistry/blob/master/EventRegistry/QueryStory.py

```python
    """
    [...]
    @param eventUriOrUriList: a single story uri or a list of story uris
    """
    def __init__(self, storyUriOrList = None):
```
The param name is `storyUrlOrList` in the code and it is `eventUriOrUriList` in the docstring.

**Comment by gregorleban** [comment]
thanks for the input, I've just fixed it.
