### ISSUE TITLE
Query with multiple search terms

### ISSUE THREAD

**Issue by sruteesh** [gregorleban/EventRegistry#10]
Hello,
Thanks for the great tool.
I plan to get all the articles(atleast the count) matching a query (ex: "Angelique kerber US open")
but since the query is converted to concept URI, Is there a way I can query multiple keywords.

Also the mentions count in news and social media doesn't seem to work for social media(It works great for the news though). It always returns me 0 count. Is there any issue around social media data?
Thank you.

**Comment by gregorleban** [comment]
Sorry for being extremely late on responding to this question.

I think you are not understanding correctly how queries are made. When you make a query you can search by multiple types of conditions. One of the condition types is concept URIs. Another way how you can make the queries is directly by keywords. If you check the parameters that the QueryEvents and QueryArticles accepts you'll see that you can specify conceptUri as well as keywords. 

So, in your case, to search for the given set of keywords simply set keywords = "Angelique kerber US open"

which API call are you referring to when you say that the social media counts don't work? If you are referring to GetCounts, then as you can see in the documentation, it only works for concepts or categories.
