### ISSUE TITLE
LocationFlag for articles returns 'None' always

### ISSUE THREAD

**Issue by sruteesh** [gregorleban/EventRegistry#14]
I have tried multiple searches using different conceptURI. I have always received 'None' as location even though i set the flag in locationFlags. Please help.
Thanks

**Comment by gregorleban** [comment]
Try making a query where you search for articles for which we have extracted location, i.e.:

```QueryArticles(locationUri = er.getConceptUri("London"))```

The location on the article is defined only in the cases when we are able to extract the location from the dateline of the article - this is a minority of the articles.

If you wish to find the location where the event mentioned in the article happened you can check if the article is a member of an event (check eventUri value in the article). If it is, load the event information and check the location of the event - for most of the events we are able to extract the location (based on all the articles in the event).
