### ISSUE TITLE
Get source of events

### ISSUE THREAD

**Issue by xiaoylu** [gregorleban/EventRegistry#15]
Hi,

I am trying to track the information flow in news media. Specifically, I download all the articles belonging to a particular event and find out the sources of these articles. For example, articles a,b and c are clustered as one event by EventRegistry. So, I would like to know the source of a, the source of b and the source of c.

But the issue is that the daily limitation on the number of queries for the _event with **all** the articles inside_ is 2000. It takes one query to download **all the articles** of each event. Using this approach, I can track the flow of 2000 events per day only.

Is there any way I can download more in one day? The article content is not very important to me. I just need the timestamp and sources of all the articles inside one event. I was thinking about downloading as many articles as possible (that gives me 2000 queries per day \* 200 articles per query) and then find out all the articles belonging to the same events on my machine locally. Would this approach work?

Thanks in advance.

**Comment by gregorleban** [comment]
Hi,
there are two options how you can get an increased count. One is to create a paid subscription in which you would pay for the number of the requests that you make and the number of returned items (events, articles). If you are doing this as a researcher with the aim of creating a publication then we offer also an option where we can run the queries for you in exchange for co-authorship on the paper.
