### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Analect** [gregorleban/EventRegistry#2]
@gregorleban 
I was running through various examples from the wiki ... but haven't had any success in articles returning.  Just keep getting "No JSON object could be decoded".  I'm wondering am I doing something wrong? Thanks.

**Comment by gregorleban** [comment]
Hi,
can you provide me a code sample that did not return valid json object?
Best,
Gregor

**Comment by Analect** [comment]
OK, just took this example from the wiki ... it was using "Star Wars" ... and changed to "Donald Trump" and both giving me back the "No JSON object could be decoded"

```
from eventregistry import *
er = EventRegistry()
q = QueryEvents()
q.addConcept(er.getConceptUri("Donald Trump"))   
q.addRequestedResult(RequestEventsInfo(sortBy = "date", count=10))   # return event details for last 10 events
print er.execQuery(q)
```

**Comment by gregorleban** [comment]
Can you make sure that you are using the latest code from github or the latest version from pypi. The example that you provided works fine with me. Let me know if this fixes the issue, otherwise try providing me more information which python are you using, OS, ...

**Comment by Analect** [comment]
Hmmm.  Here are details of what I did.
OS is linux .. on Virtualbox running 14.04
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
```
Initially cloned repo from github, set up a virtualenv and attempted 'python setup.py install'
This failed .. not sure why ... perhpas its a capitalisation issue ... as there is a directory EventRegistry?
```
$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to eventregistry.egg-info/requires.txt
writing eventregistry.egg-info/PKG-INFO
writing top-level names to eventregistry.egg-info/top_level.txt
writing dependency_links to eventregistry.egg-info/dependency_links.txt
error: package directory 'eventregistry' does not exist
```

Anyway, within the virtualenv, then ran a simple pip install eventregistry, which appeared to work.

```
(env)$ pip install eventregistry
Collecting eventregistry
/home/mccoole/Development/Tools/misc/EventRegistry/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading eventregistry-6.0.3.zip
Collecting requests (from eventregistry)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 503kB 53kB/s 
Building wheels for collected packages: eventregistry
  Running setup.py bdist_wheel for eventregistry
  Stored in directory: /home/mccoole/.cache/pip/wheels/5f/5d/04/f1083ff9d697aeb891850e9f85812aed5465114798e90fc8c9
Successfully built eventregistry
Installing collected packages: requests, eventregistry
Successfully installed eventregistry-6.0.3 requests-2.9.1
/home/mccoole/Development/Tools/misc/EventRegistry/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```
Not sure if this gives you enough to go with. Thanks.

**Comment by gregorleban** [comment]
could you try running:

pip install eventregistry --upgrade

I've made an updated package today - maybe this will fix the issue. Otherwise I'm not sure what could be the issue. Let me know if this updating helps, otherwise we'll try to find other solutions.

**Comment by Analect** [comment]
@gregorleban 
I did that upgrade ... and things are looking a little more encouraging ...
But I'm bumping up against a limit
```
You have reached the request limit for unregistered users (20 requests per day). Login or register (it's free!) in order to be able to make 1000 requests per day.
```
I have registered as a user ... but it's not clear from the docs how I pass my credentials using this python library ... I can see there's some reference to a settings.json file that might contain these ... could you elaborate?  Thanks

**Comment by gregorleban** [comment]
Great about the fixed issue. Regarding the logging in, here is the wiki info:
https://github.com/gregorleban/EventRegistry/wiki/EventRegistry-class#logging-in

**Comment by Analect** [comment]
Sorry ... missed that part of the docs.
That upgrade appears to have resolved my issue. Thanks very much.
I'll close this out. Rgds. Colum
