### ISSUE TITLE
Accessing articles from an event

### ISSUE THREAD

**Issue by riedelcastro** [gregorleban/EventRegistry#3]
I am performing an event query, and what to see the articles associated with a given event. Somehow I can't see this information in the returned result, or find relevant information on the wiki. Did I miss this?

**Comment by riedelcastro** [comment]
Never mind, I think I found it: do QueryEvents, then get the Query URIs, then do QueryEvent with corresponding request info?

**Comment by gregorleban** [comment]
There should be two requests used (as you wrote your post it seems you are doing three):
- first QueryEvents where you ask for RequestEventsUriList()
- for each obtained event URI you can call QueryEvent where you ask for RequestEventArticles
let me know if you need more info.

**Comment by riedelcastro** [comment]
Yes, that's what I meant, works perfectly. Thanks much for a great tool and resource.
