### ISSUE TITLE
Correlations - setCustomInputData issue

### ISSUE THREAD

**Issue by mkarlovc** [gregorleban/EventRegistry#4]
Variable `val` and `count` confused in `def setCustomInputData(self, inputDataArr):`
https://github.com/gregorleban/EventRegistry/blob/master/EventRegistry/Correlations.py#L35

**Comment by gregorleban** [comment]
This was fixed.

**Comment by markoarnauto** [comment]
As far as I can see, the variables `val` and `count` are still mixed up in the `setCustomInputData`.

**Comment by gregorleban** [comment]
the correlations feature was discontinued so the issue is no longer relevant.
