### ISSUE TITLE
not json serialisable

### ISSUE THREAD

**Issue by surank** [gregorleban/EventRegistry#7]
I'm testing code from the wiki 
# !/usr/local/bin/python3.5

from eventregistry import *
er = EventRegistry()

q = GetTrendingConcepts(source="news",count=10)
print(er.execQuery(q))

I keep getting error 
TypeError: b'news' is not JSON serializable

**Comment by gregorleban** [comment]
er.execQuery returns you a dictionary. If you want to print it, use:

ret = er.execQuery(q)
print(er.format(ret))

this at least works on python 2.7.

**Comment by surank** [comment]
yeah still doesnt work i tried interactively it does not like the line 'ret='

**Comment by gregorleban** [comment]
this issue should now be fixed with the latest version of the module.
