### ISSUE TITLE
Downloading Articles related to an Event

### ISSUE THREAD

**Issue by girishk14** [gregorleban/EventRegistry#8]
Hi,

I have been able to use a combination of QueryEvents along with ReturnInfo flags to get a list of events that occurred in a particular time period.

I have enabled the flag for stories, however, I am unable to find all the articles pertaining to a story, and I can only the medoid article for that story.

Is there a way to get all the links to the articles about an event?

**Comment by gregorleban** [comment]
QueryEvents can only provide info about the events and some aggregates (classes specified in QueryEvents.py). Once you have some event URIs for which you'd like articles, you can then request details about individual event (including articles) using QueryEvent() class. Sample code for getting articles from events about Donald Trump is below:

```
trumpUri = er.getConceptUri("Trump")
q = QueryEvents(conceptUri = trumpUri)
q.addRequestedResult(RequestEventsUriList())
eventUriListRet = er.execQuery(q)
eventUriList = eventUriListRet["uriList"]["results"]
for eventUri in eventUriList:
    page = 1
    while True:
        q = QueryEvent(eventUri)
        q.addRequestedResult(RequestEventArticles(page = page, count = 50, returnInfo = ReturnInfo(articleInfo = ArticleInfoFlags(body = False))))
        res = er.execQuery(q)
        articleList = res[eventUri]["articles"]["results"]
        page += 1
        if page > res["articles"]["pages"]:
            break
```

`articleList` in this case would contain the list of articles for the queried event.

One thing to keep in mind is that you might have incorrect understanding of the term story. I suggest you check the https://github.com/gregorleban/EventRegistry/wiki/Terminology#story page.

**Comment by girishk14** [comment]
Thank you so much! I was unable to find QueryEvent anywhere in the Wiki Documentation, so I was using QueryEvents instead!

**Comment by gregorleban** [comment]
How to get available information about an event is described on this page:
https://github.com/gregorleban/EventRegistry/wiki/Get-event-information
